CFLAGS = -std=c99 -Wall -Wextra -D_GNU_SOURCE
CC = gcc
GDB = gdb
BUILD_DIR = build
RAYLIB_DIR = ./vendor/raylib/src/
RAYLIB_OPTIONS = PLATFORM=PLATFORM_DESKTOP
BUILD_MODE = DEBUG

GAME_CFLAGS = $(CFLAGS) -DMAX_GAMEPAD_BUTTONS=32
GAME_INCLUDES = -isystem $(RAYLIB_DIR)
GAME_OPTIONS = -DOS_IMPLEMENTATION_LINUX -DMEMORY_MMAP -DLOG_IMPLEMENTATION -DARENA_IMPLEMENTATION
GAME_LDLIBS = -L$(RAYLIB_DIR) -l:libraylib.a -lGL -lm -lpthread -ldl -lrt -lX11

.PHONY: run debug clean

ifeq ($(BUILD_MODE),DEBUG)
    CFLAGS += -g -O0 -DDEBUG -DENABLE_ASSERT
	RAYLIB_OPTIONS += RAYLIB_BUILD_MODE=DEBUG
endif

ifeq ($(BUILD_MODE),RELEASE)
    CFLAGS += -Os
	RAYLIB_OPTIONS += RAYLIB_BUILD_MODE=RELEASE
endif

run: game
	./$(BUILD_DIR)/pong

game: pong.c deps
	mkdir -p $(BUILD_DIR)
	$(CC) pong.c -o $(BUILD_DIR)/pong $(GAME_CFLAGS) -I$(BUILD_DIR) $(GAME_INCLUDES) $(GAME_LDLIBS) $(GAME_OPTIONS)

deps:
	$(MAKE) -C $(RAYLIB_DIR) $(RAYLIB_OPTIONS)

clean:
	$(MAKE) -C $(RAYLIB_DIR) clean
	$(RM) -rf $(BUILD_DIR)
